from typing import Any

__version__: str

def deserialize(toml: str) -> Any: ...
def serialize(obj: Any) -> str: ...
def serialize_pretty(obj: Any) -> str: ...

class TomlParsingError(ValueError): ...
class TomlSerializationError(ValueError): ...
