from typing import Any

__version__: str

def deserialize(toml: str, none_value: str | None = None) -> Any: ...
def serialize(obj: Any, none_value: str | None = 'null') -> str: ...
def serialize_pretty(obj: Any, none_value: str | None = 'null') -> str: ...

class TomlParsingError(ValueError): ...
class TomlSerializationError(ValueError): ...
